name: 'Generate ADR TOC'
description: 'Generates the Table of Contents for ADRs'

inputs:
  adr-dir:
    description: 'Directory of the ADR'
    required: false
    default: ''
  adr-tool-repo:
    description: 'Repo to the ADR Tools. Must be HTTPS url'
    required: false
    default: 'https://github.com/npryce/adr-tools.git'
  adr-tool-version:
    description: 'Version from the ADR Tools Repo'
    required: false
    default: '3.0.0'

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v2

    - name: Clone ADR Tools
      run: git clone --depth 1 --branch ${{ inputs.adr-tool-version }} --single-branch ${{ inputs.adr-tool-repo }} adr-tools

    - name: Install Graphviz
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          brew install graphviz
        else
          sudo apt-get install graphviz
        fi

    - name: Run ADR Tools
      run: |
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
        ADR_DIR = "${{ inputs.adr-dir }}"
        if [ -z "$ADR_DIR" && -f .adr-dir ]
        then
          ADR_DIR="$(cat .adr-dir)"
        else
          echo '.adr-dir file doesnt exist, and no adr-dir input was given into the action. Please define one'
          exit 1
        fi

        pushd $ADR_DIR

        # Generate Graph of ADRs
        "$DIR/adr-tools/src/adr" generate graph | dot -Tpng > graph.png

        # Add content to README, including generated TOC
        echo "<!-- This file is autogenerated by actions, please don't modify it -->" > README.md
        "$DIR/adr-tools/src/adr" generate toc >> README.md
        echo -e '\n\n## Dependency Graph of ADRs\n\n![ADR Graph Dependency](graph.png)' >> README.md

        popd

    - name: Commit ADR TOC
      run: |
        .github/support/commit.sh "Update ADR TOC" \
          "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.repository }}" \
          ${{ github.ref }} \
          "${{ inputs.adr-dir }}/*"
